services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file: 
      - .env
    environment:
      ConnectionStrings__Library: Host=db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

